# Generated by Django 3.2.2 on 2021-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
