version: "3.8"

services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: neustren/nginx_fusion:v1
    container_name: nginx
    ports:
      - "8003:80"
    networks:
      - nwfusion
    depends_on:
      - fusion1
      - fusion2
      - fusion3

  pgfusion:
    build:
      dockerfile: ./docker/pgfusion.dockerfile
      context: .
    image: neustren/pgfusion:v1
    container_name: pgfusion
    ports:
      - "5432"
    networks:
      - nwfusion
    volumes:
      - pgdata:/var/lib/postgresql/data/

  fusion1:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: neustren/fusion:v1
    container_name: fusion1
    ports:
      - "8002"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  fusion2:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: neustren/fusion:v1
    container_name: fusion2
    ports:
      - "8002"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  fusion3:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: neustren/fusion:v1
    container_name: fusion3
    ports:
      - "8002"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

networks:
  nwfusion:
    driver: bridge

volumes:
  pgdata:
