# Generated by Django 3.1.7 on 2021-03-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='modificado',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='ativo',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativo?'),
        ),
    ]
