# Generated by Django 3.1.7 on 2021-03-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210327_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, null=True, verbose_name='Ativo?')),
                ('source_slug', models.CharField(max_length=255)),
                ('source_url_global', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=255)),
                ('source_initial_timer', models.IntegerField(null=True)),
                ('source_regex', models.CharField(max_length=255, null=True)),
                ('source_category', models.CharField(max_length=255, null=True)),
                ('news_source', models.CharField(max_length=255)),
                ('news_container', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.CharField(max_length=255, null=True)),
                ('news_date', models.CharField(max_length=255, null=True)),
                ('news_category', models.CharField(max_length=255, null=True)),
                ('news_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fonte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.fonte'),
        ),
    ]
