# Generated by Django 3.1.7 on 2021-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20210401_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='source_slug',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
