# Generated by Django 3.2.2 on 2021-05-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20210419_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, null=True, verbose_name='Ativo?')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
