# Generated by Django 3.2.2 on 2021-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonte',
            name='linguagem',
            field=models.CharField(choices=[('PT', 'Portugues'), ('EN', 'Inglês'), ('FR', 'Francês'), ('ES', 'Espanhol'), ('IT', 'Italiano'), ('RU', 'Russo'), ('DE', 'Alemão')], default='PT', max_length=2),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
