# Use root/example as user/password credentials
version: "3.2"

services:
  mongo:
    image: mongo
    container_name: tweeze-mongo
    restart: always
    ports:
      - "27037:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tweezeauth
      - MONGODB_USERNAME=tweezeauth
      - MONGO_INITDB_ROOT_PASSWORD=admin777
      - MONGODB_PASSWORD=admin777
    volumes:
      - ./db/docker/Volumes/MongoDB:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: tweeze-mongo-express
  #   restart: always
  #   ports:
  #     - 27031:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=tweezeauth
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin777
  #     - ME_CONFIG_MONGODB_PORT=27037
  #     - ME_CONFIG_BASICAUTH_USERNAME=tweezeauth
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin777
