# Generated by Django 3.1.7 on 2021-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210327_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.TextField(),
        ),
    ]
