# Generated by Django 3.1.7 on 2021-03-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210330_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='source_id',
            new_name='fonte',
        ),
    ]
