# Generated by Django 3.1.7 on 2021-04-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210401_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='source_type',
            field=models.CharField(choices=[('XML', 'XML'), ('HTML', 'HTML')], max_length=255),
        ),
    ]
