# Generated by Django 3.1.7 on 2021-04-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210402_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='source_slug',
            field=models.CharField(max_length=255),
        ),
    ]
