# Generated by Django 3.1.7 on 2021-03-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210327_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='criados',
        ),
    ]
