# Generated by Django 3.1.7 on 2021-03-27 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_noticia_criados'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='modificado',
            field=models.DateField(auto_now=True, null=True, verbose_name='Atualização'),
        ),
    ]
