# Generated by Django 3.1.7 on 2021-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210330_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='titulo',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='fonte',
            new_name='source_id',
        ),
        migrations.AddField(
            model_name='noticia',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
