# Generated by Django 3.1.7 on 2021-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20210407_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonte',
            name='news_category',
        ),
        migrations.RemoveField(
            model_name='fonte',
            name='news_date',
        ),
        migrations.RemoveField(
            model_name='fonte',
            name='news_description',
        ),
        migrations.RemoveField(
            model_name='fonte',
            name='news_title',
        ),
        migrations.AddField(
            model_name='fonte',
            name='source_municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Município de Origem da Fonte'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='news_container',
            field=models.CharField(max_length=255, verbose_name='Container das notícias'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='news_source',
            field=models.CharField(max_length=255, verbose_name='Nome da Fonte'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='news_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Elemento da Url'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoria da Fonte'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_initial_timer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo Inicial'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_regex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Base da URL (Facultativo)'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_slug',
            field=models.CharField(max_length=255, verbose_name='Slug da Fonte'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_state',
            field=models.CharField(blank=True, choices=[('INT', 'Mundo'), ('EUR', 'Europa'), ('AME', 'América'), ('OCE', 'Oceania'), ('AFR', 'África'), ('BR', 'Brasil'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=3, null=True, verbose_name='Estado de Origem da Fonte'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_type',
            field=models.CharField(choices=[('XML', 'XML'), ('HTML', 'HTML')], max_length=255, verbose_name='Tipo de Fonte'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='source_url_global',
            field=models.CharField(max_length=255, verbose_name='Link geral da Fonte'),
        ),
    ]
