# Generated by Django 3.2.2 on 2021-05-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gruposdepalavras_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposdepalavras',
            name='grupo',
            field=models.CharField(default='Novo', max_length=64),
            preserve_default=False,
        ),
    ]
